Create database TuesdayTask;
use TuesdayTask;
Create TABLE Electronics_Goods_details (SL_NO INT,NAME VARCHAR(50) UNIQUE,COMPANY_NAME VARCHAR(50) UNIQUE,LIFE VARCHAR(50) UNIQUE,MODEL VARCHAR(50) UNIQUE,
SHOP_NAME VARCHAR(50) UNIQUE,SHOP_OWNER_NAME varchar(50)unique,SHOP_OWNER_FATHER_NAME VARCHAR(50) UNIQUE,SHOP_GST_NO BIGINT UNIQUE,
SHOP_NUM BIGINT UNIQUE,PRICE BIGINT NOT NULL,SHOP_LOCATION VARCHAR(50) UNIQUE,SHOP_TALUK_NAME VARCHAR(50) UNIQUE,SHOP_DIST_NAME VARCHAR(50) UNIQUE,
STATE_NAME VARCHAR(50),COUNTRY_NAME VARCHAR(50),LIFE_SPAN VARCHAR(50)UNIQUE,is_checked BOOLEAN,PRODUCT_QUALITY BOOLEAN,BUYER_NAME VARCHAR(50)UNIQUE,
BUYER_LOACTION VARCHAR(50)UNIQUE,BUYER_STATE VARCHAR(50));
DROP TABLE Electronics_Goods_details;
INSERT INTO Electronics_Goods_details VALUES(1,'TV','SONY','5_YEARS','XPERIA','HANJANADRI ELE','SUNIL','SANGAPPA',789651,9844457917,15000,'MOTI CIRCLE','BALLARI','BALLARI','KARANATAKA','INDIA','DEPEND USABLE',TRUE,TRUE,'SHASHI','CHITRADURGA','KA');
INSERT INTO Electronics_Goods_details VALUES(2,'PHONE','MOTO','4_YEARS','MOTO G','SANGEETHA ELE','AISHU','KRISHAN',456987,8431081485,12000,'HINKAL','MYSORE','MYSORE','KARANATAKA','INDIA','DEPENDS',TRUE,TRUE,'CHIRAG','MYSORE','KAR');
INSERT INTO Electronics_Goods_details VALUES(3,'WASHING MACHINE','KETTLE','10_YEARS','XPBUTTERFLYE','D-MART','CHIRAG','KRISHAN NAYAK',123123,9972673153,12000,'VIJAYACIRCLE','MYSORIAN','MYSORIAN','KARANATAKA','INDIA',' USABLE',TRUE,TRUE,'ICECREAME','MYSORIAN','KARN');
INSERT INTO Electronics_Goods_details VALUES(4,'FRIDGE','LG','1_YEARS','DOUBLE DOOR','D-MART VIJ','SHASHI','BASUVARAJAPPA',789652,984445791,14000,'MOTI','BANGALORE','BANGALORE','KARANATAKA','INDIA','USABLE',TRUE,TRUE,'PRASHANTH','SHIVAMOHHGGA','KARNA');
INSERT INTO Electronics_Goods_details VALUES(5,'LAPTOP','DELL','6+YEARS','CORE-i5','CAPSLOCK ELE','ARUN','KASHINATH',789612,9844457781,21000,'MOTI-CIRCLE','VIJAYANAGAR','VIJAYANAGAR','KARANATAKA','INDIA','DEPEND-USABLE',TRUE,TRUE,'SHIVU','VIJAYANAGAR','KA');
INSERT INTO Electronics_Goods_details VALUES(7,'KETTLE','OMG','11_YEARS','ZXCDSA','MANJUNATH ELE','AKASH','MANJUNATH',852741,9822457917,14014,'RAYA CIRCLE','HADAGALI','HADAGALI','KARANATAKA','INDIA','DEPEND/SABLE',TRUE,TRUE,'VARUN','HADAGALI','KA');
INSERT INTO Electronics_Goods_details VALUES(8,'OWEN','CNG','12_YEARS','ASDFGHJ','SHANBOG ELE','ravitej','RANGAPPA',789123,9844457123,15123,'ROYAL CIRCLE','BALLARIAN','BALLARIAN','KARANATAKA','INDIA','DEPEND&USABLE',TRUE,TRUE,'SANGEETHA','BALLARIAN','KA');
INSERT INTO Electronics_Goods_details VALUES(9,'HEATER','ONIDA','13_YEARS','ZXCVB','MALLIGE ELE','CHAITRA','MANJUTHA C',78961234,9844451234,11234,'M-CIRCLE','CHANPTNA','CHANPATNA','KARANATAKA','INDIA','DEPEND&&USABLE',TRUE,TRUE,'CHITRA','CHANPTNA','KA');
INSERT INTO Electronics_Goods_details VALUES(10,'ELECTRIC STOVE','AMD','14_YEARS','UJNYHTG','GIRIHS ELE','GAGAN','VISHWANATH',789234,9844457234,15234,'MOTI>CIRCLE','SHIVMOGGA','SHIVMOGGA','KARANATAKA','INDIA','DEPEND/USABLE',TRUE,TRUE,'SAGAR','SHIVMOGGA','KA');
INSERT INTO Electronics_Goods_details VALUES(11,'CHARGER','UG','15_YEARS','QWERT','ANAND ELE','SAGAR','VISHWANATH SAGAR',789987,9844457987,15999,'PUNNETH CIRCLE','SHIVMOG','SHIVMOG','KARANATAKA','INDIA','DEPEND@USABLE',TRUE,TRUE,'GAGAN','SHIVMOG','KA');
INSERT INTO Electronics_Goods_details VALUES(12,'FAN','SUPREEM','16_YEARS','SDQWERD','SIMHADRI ELE','VARUN','VARUN SHARAN',789258,984445258,15777,'APU CIRCLE','HOSPET','HOSPET','KARANATAKA','INDIA','@USABLE',TRUE,TRUE,'SHARAN','HOSPET','KA');
INSERT INTO Electronics_Goods_details VALUES(13,'ALEXA','ANGULAR','17_YEARS','YIPOIU','LAKXMI ELE','RAJITHA','RAYAN',789147,9844457147,155147,'MADHAPUR CIRCLE','TAGMUTHI','MADHAPUR','HYDERBAD','INDIA',' **USABLE',TRUE,TRUE,'AJITHA','MOSAKODU','TA');
INSERT INTO Electronics_Goods_details VALUES(14,'AC','BOAT','18_YEARS','HJKJHGFGH','ANMARG ELE','MANI','DEEPTHINKER',789741,9844457741,15741,' EL CIRCLE','BHIMAVARAM','BHIMAVARAM','HYDERBAD','INDIA','DEPEND$$USABLE',TRUE,TRUE,'AYYAPPPA','BHIMAVARAM','KA');
INSERT INTO Electronics_Goods_details VALUES(15,'SMARTWATCH','NOISE','19_YEARS','SDFGHGFERT','SSS ELE','SACHINE','RAJANNA',875258,977445258,14777,'ID CIRCLE','HB HALLI','VIJAYANAGAR HOS','HYDERBAD','INDIA','USABLE MOOD',TRUE,TRUE,'SWETHA','KITTURU','KA');
INSERT INTO Electronics_Goods_details VALUES(16,'PEOJECTOR','MOISE','21_YEARS','UJNFGHJK','NILMAYA ELE','NAVEEN','BAILAPPA',789321,9844457321,14888,'SANGAM CIRCLE','BELLARI','BELLARI','KARANATAKA','INDIA','DEPEND>USABLE',TRUE,TRUE,'NAMETHA','BELLARI','KA');
INSERT INTO Electronics_Goods_details VALUES(17,'DVD','DUBAX','20_YEARS','TYUI','SUNIL ELE','VEERU','VEERESH',78968,9844457965,14999,'BASAVESWARA CIRCLE','HBH','HBH','KARANATAKA','INDIA','DEPEND8USABLE',TRUE,TRUE,'RAVI','HBH','KA');
INSERT INTO Electronics_Goods_details VALUES(18,'RADIO','FMBOX','22_YEARS','JHGFIK','SHREYAN ELE','SAMMU','PRAKASHU',789221,9844457221,13999,'@APPU CIRCLE','HAGABOMANAHALLI','@VIJAYANAGAR','KARANATAKA','INDIA','DEPEND89USABLE',TRUE,TRUE,'SANKALPA','HAGABOMANAHALLI','KA');
INSERT INTO   Electronics_Goods_details VALUES(19,'ELE STOVE','BLEE','3_YEARS','MNBCFGHH','ARUN ELE','SHUBHAM','SHUBHAM',789331,984445331,11999,'SOUTH CIRCLE','SOUTH','SOUTH','KARANATAKA','INDIA','DEPENDABLE',TRUE,TRUE,'AKSHAY','GULBARGA','KA');
INSERT INTO Electronics_Goods_detailsdetails VALUES(20,'STAIGHTING MACHINE','AMAZONE','7_YEARS','QWASEW','GAGAN ELE','SHIVU','KASHINTHA',789112,984445712,10999,'MAIN BAZAR','ROYAL VIJAYANAGARA','ROYAL VIJAYANAGARA','KARANATAKA','INDIA','DEPENDS USAGE',TRUE,TRUE,'ARUN','ROYAL VIJAYANAGARA','KA');

SELECT * FROM Electronics_Goods_details;

/*===================================================================================================================================================================
============================================================================================================================================*/

CREATE TABLE RETAILER_DETAILES(idno int,RETAILER_NAME varchar(50) unique,RETAILER_AGE int,RETAILER_LOCATION varchar(50)unique,
RETAILER_VILLAGE varchar(50),RETAILER_TALUK VARCHAR(50)UNIQUE,RETAILER_DIST varchar(50),RETAILER_STATE varchar(50),
RETAILER_COUNTRY varchar(50),RETAILER_PRODUCT_NAME VARCHAR(50)UNIQUE,RETAILER_GST_NUM VARCHAR(50)UNIQUE,RETAILER_FAMOUS_FOR VARCHAR(50)UNIQUE,RETAILER_DISCOUNT_PER VARCHAR(50)UNIQUE
,RETAILER_VECHILE_NUM VARCHAR(50)UNIQUE,RETAILER_BRO_NAME VARCHAR(50)UNIQUE,RETAILER_SIS VARCHAR(50)UNIQUE,RETAILER_FRNDS VARCHAR(50)UNIQUE,
RETAILER_QULIFICATION VARCHAR(50),RETAILER_NUM BIGINT UNIQUE,RETAILER_INCOME BIGINT UNIQUE);

insert into RETAILER_DETAILES values(1,'Shashi',25,'Hospet','Hampasagar','Hospet','Vijayanagar','KA','INDIA','SUGAR','789651','SUGAR','25% DISCOUNT PER BAG','KA35HH1234','MINI','MRUDHULA','SHASH','BE',98745697485,50000);
insert into RETAILER_DETAILES values(2,'JOsh',21,'Vijayanagar','Hampasagar','Vijayanagar','Vijayanagar','AP','INDIA','RICE','AZYY2224','RICE','15% DISCOUNT PER BAG','KA35HH2234','SHEYAN','NAYANA','SHREE','B.ENGG',9874564566,6550);
insert into RETAILER_DETAILES values(3,'Aishu',20,'Mysore','Mysore','Mysore','Mysore','KA','INDIA','WHEET','AZYY2234','WHEET','10% DISCOUNT PER BAG','KA35HH1254','SAMPREETH','MALLIKARJUN','HAISH','BCA',98745698721,5550);
insert into RETAILER_DETAILES values(4,'Shree',20,'Sampekatte','Sampekatte','Shivamogga','Hosagnagar','KA','INDIA','JOWAR','AZYY2235','JOWAR','12% DISCOUNT PER BAG','KA35HH1264','SHRISHAM','CHAITRA','SRIDHAR','MCOM',98745698227,4150);
insert into RETAILER_DETAILES values(5,'harsha',26,'Hireyhuru','Hosadurga','Hosadurga','Durga','KA','INDIA','AC','AZYYL5524','AC','5% AC','KA35HH1299','PRADEEP','PRAKRUTHI','MACHEDAR','MBBS',987692187,54999);
insert into RETAILER_DETAILES values(6,'Chaitra',24,'Chaptnaa','Noise city','Channapatnaa','RamDurga','KA','INDIA','COOLER','AZYY2129','COOLER','13% PER COOLER','KA35HH1232','VISHWANATH','DHANU','PAVAN','MS',9874569876,65999);
insert into RETAILER_DETAILES values(7,'Neeraj',25,'Sondur','Sondur','Sondur','Ballari','KA','INDIA','BUSSINES IN ALL','AZYY2128','BUSSINES','10% ONLY FOR ALL','KA35AH1222','MANU','LAVANYA','NAGRAJ','MTECH',98745698447,89999);
insert into RETAILER_DETAILES values(8,'Nataraj',24,'Matthodu','Hosadrga','Hosadrga','Durgaa','KA','INDIA','RICE SAILING','AZYY2127','RICE SAILING','25% DISCOUNT','KA35HH1266','KARTHIK','AJITHA','TEJA','BTECH',987056987,78888);
insert into RETAILER_DETAILES values(9,'Shubaham',21,'Kenada','america','USA','Vijayanagar','KA','INDIA','DAAL','AZYY2126','DAAL','35% DISCOUNT PER BAG','KA35HH1255','SANKALPA','RAJITHA','SHREYAN','LLB',9870698227,56666);
insert into RETAILER_DETAILES values(10,'Navya',22,'WS','ZOMOTO','SWIGGGY','SPONSEE','KA','INDIA','GROUD NUT','AZYY2125','GROUD NUT','40% DISCOUNT PER BAG','KA35HH1222','SAMMU','AISHU','SUNIL','MCA',98745692187,22222);
insert into RETAILER_DETAILES values(11,'Crazy',23,'HYD','HYD','HYD','HYD','TS','INDIA','CHAIRS','AZYY2124','CHAIRS','13% DISCOUNT PER CHAIRS','KA35HH1236','VEERESH','AFREEN','CHETHAN','BCA',98745666987,55555);
insert into RETAILER_DETAILES values(12,'Sonu',24,'Harpanalli','Harpanalli','Harpanalli','Vijayanagar','KA','INDIA','PLASTIC','AZYY2123','PLASTIC','19% DISCOUNT PER PLASTIC BAG','KA35HH2134','NAVEEN','WASEEQA','SHIVU','BSC',9587456987,5000);
insert into RETAILER_DETAILES values(13,'Killer',22,'BLY','BLY','BLY','BLY','KA','INDIA','PHONE','AZYY2236','PHONE','20%','KA35HH1274','SHASHI','SWETHA','SHREEKANTH','BE',98745692287,9500);
insert into RETAILER_DETAILES values(14,'Akash',23,'HOSAPETE','Hampasagar','HOSAPETE','Vijayanagar','KA','INDIA','TV','AZYY2237','TV','21% ','KA35HH1284','SHUBRMANYA','JOSH','PRAKASH','BE',987456222987,2500);
insert into RETAILER_DETAILES values(15,'Love',21,'HYDBAD','HYDBAD','HYDBAD','HYDBAD','TS','INDIA','FRIDGE','AZYY2238','FRIDGE','30%','KA35HH1294','SATHISPREAVVEN','SHAHANA','HARISH','BCOM',98742256987,85000);
insert into RETAILER_DETAILES values(16,'Afreen',22,'HSPT','HSPT','HSPT','Vijayanagar','KA','INDIA','HEATER','AZYY2239','HEATER','50% ON TWO','KA35HH1104','BHUNASHEKAR','RAMYA','NEERAJ','BSC',98746987,75500);
insert into RETAILER_DETAILES values(17,'Arun',25,'UUSK ','UUSK','UUSK','UUSK','KA','INDIA','SOLAR','AZYY2240','SOLAR','BUY ONE GET ONE','KA35HH1114','SUHAS','NAVYA','SUHAS','MD',98745226987,6500);
insert into RETAILER_DETAILES values(18,'VArun',24,'KAmmadni','raichuru','raichuru','raichuru','KA','INDIA','CARRAOM','AZYY2241','CARRAOM','74%  PER BOARD','KA35HH1124','RAVITEJ','REKHA','RAVITEJ','MCA',98227456987,5500);
insert into RETAILER_DETAILES values(19,'Sachine',24,'Shivamoga','Shivamogga','Shivamoga','Shivamogga','KA','INDIA','PLAYING','AZYY2242','PLAYING','20% RACH GANE','KA35BB1234','UDYA','DIMPLE','SHASHI','DIPLOMA',98745695587,3500);
insert into RETAILER_DETAILES values(20,'Chethan',26,'Mudhol','Mudhol','Mudhol','Mudhol','KA','INDIA','BOTTLES','AZYY2243','BOTTLES','18% DISCOUNT PER BOTTLE','KA35HH234','SACHINE','KILLER','ARUN','PUC',98755456987,4500); 

SELECT * FROM  RETAILER_DETAILES;
/*===================================================================================================================================================================
============================================================================================================================================*/

 select IDNO ,sl_nO from Electronic_Good inner join RETAILER_DETAILES where IDNO=sl_nO;
select IDNO ,sl_nO from Electronic_Good left join RETAILER_DETAILES on IDNO=sl_nO;
select IDNO ,sl_nO from Electronic_Good right join RETAILER_DETAILES on IDNO=sl_nO;
select IDNO ,sl_nO from Electronic_Good , RETAILER_DETAILES;

SELECT * FROM RETAILER_DETAILES;
SELECT * FROM Electronic_Good;

ALTER TABLE RETAILER_DETAILES ADD COLUMN  RETAILER_NAME VARCHAR(70)DEFAULT "Dontno";
ALTER TABLE RETAILER_DETAILES MODIFY COLUMN  RETAILER_INCOME BIGINT;
ALTER TABLE RETAILER_DETAILES RENAME COLUMN  RETAILER_QULIFICATION TO RETAILER_EDUCATION;
ALTER TABLE RETAILER_DETAILES DROP COLUMN  RETAILER_EDUCATION ;
DESC RETAILER_DETAILES;
   
SELECT  RETAILER_NAME FROM RETAILER_DETAILES WHERE idno=3;
SELECT RETAILER_NAME FROM RETAILER_DETAILES WHERE idno BETWEEN 1 AND 3;
SELECT RETAILER_NAME FROM RETAILER_DETAILES WHERE idno NOT IN (1,5);
SELECT RETAILER_NAME FROM RETAILER_DETAILES WHERE idno =5 AND available=0;
SELECT RETAILER_NAME FROM RETAILER_DETAILES WHERE idno =1 OR  idno=2;
                        
SELECT ltrim(RETAILER_NAME)FROM RETAILER_DETAILES;
SELECT rtrim(RETAILER_NAME)FROM RETAILER_DETAILES;

SELECT lpad("OMPI" ,15 ,"Xworkz");
SELECT rpad("KARAN" ,15 ,"Xworkz");

SELECT instr("KARAN","A") as position;
SELECT substr("Xworkz",3,4);
SELECT length("KARAN")as length;

SELECT REPLACE("KARAN", "SQL", "HTML") as REPLACING;
SELECT POSITION("R" IN "YOUTUBE") AS MATCHPOSITION;
SELECT MID("SQL Tutorial", 5, 3) AS EXTRASTRING;
SELECT REVERSE("KARAN");
select RETAILER_NAME from  RETAILER_DETAILES where RETAILER_NAME like "i%";
select RETAILER_NAME from  RETAILER_DETAILES where RETAILER_NAME between  "i"and "s";
select upper(RETAILER_NAME) from RETAILER_DETAILES;
select lower(RETAILER_NAME) from RETAILER_DETAILES;
select upper(RETAILER_NAME) from RETAILER_DETAILES where idno=1 ;
select lower(RETAILER_NAME) from RETAILER_DETAILES where idno=1 ;
select datediff("1995/02/03" , "2025/05/25")as DIFFERENCE;
select makedate(2022,31);
select date("1855/05/10");
select  date_add("2022/01/25 ,10:20:01" ,interval 10 day) as INTERVALA;
select  date_add("2013/02/15 ,11:20:01" ,interval 10 month) as INTERVALA;
select  date_add("2014/03/15 ,05:20:01" ,interval 18 quarter) as INTERVALA;
select  date_add("2015/05/21 ,01:20:01" ,interval 7 week) as INTERVALA;
select  date_add("2016/06/23 ,10:20:01" ,interval 50 second  ) as INTERVALA;
select  date_add("2017/08/29 ,10:20:01" ,interval 50 hour) as INTERVALA;
select  date_add("2018/09/21 ,10:20:01" ,interval 50 minute) as INTERVALA;
/*==========================================================================================================================*/
select  date_add("2018/09/21 ,01:20:01" ,interval -08 day) as INTERVALA;
select  date_add("2021/01/25 ,10:20:01" ,interval -5 month) as INTERVALA;
select  date_add("2021/01/25 ,10:20:01" ,interval -12 quarter) as INTERVALA;
select  date_add("2021/01/25 ,10:20:01" ,interval -9 week) as INTERVALA;
select  date_add("2021/01/25 ,10:20:01" ,interval -45 second  ) as INTERVALA;
select  date_add("2021/01/25 ,10:20:01" ,interval -22 hour) as INTERVALA;
select  date_add("2021/01/25 ,10:20:01" ,interval -31 minute) as INTERVALA;
select greatest(10,20,82,58,21,45,14)as GREATEST;
select dayname("2021/05/21")as day;

select sum(RETAILER_AGE) from RETAILER_DETAILES;
select avg(RETAILER_AGE) from RETAILER_DETAILES;
select max(RETAILER_AGE) from RETAILER_DETAILES;
select min(RETAILER_AGE) from RETAILER_DETAILES;
select count(RETAILER_AGE) from RETAILER_DETAILES;
select RETAILER_NAME from RETAILER_DETAILES group by RETAILER_AGE;
select RETAILER_NAME from RETAILER_DETAILES group by RETAILER_AGE having RETAILER_AGE=1;
select RETAILER_NAME from RETAILER_DETAILES order by RETAILER_NAME;
select RETAILER_NAME from RETAILER_DETAILES order by RETAILER_NAME desc ;

select  Mobile_Name from Electronic_Good where IDNO in (select sl_nO from RETAILER_DETAILES where sl_nO=1);
select  country from Electronic_Good where IDNO in (select sl_nO from RETAILER_DETAILES where sl_nO=1);
update Electronic_Good    set  RETAILER_AGE=25 where m_id in (select sl_nO from RETAILER_DETAILES where sl_nO=1);
delete from Electronic_Good where IDNO in (select sl_nO from RETAILER_DETAILES where sl_nO=1);
create view newview as select  E.SL_NO  ,E.MODEL,R.IDNO,R.RETAILER_COUNTRY ,R.RETAILER_VILLAGE from Electronic_Good E ,RETAILER_DETAILES R ;

